---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - packages.yml

  tasks:

  - name: Install packages
    yum: "name={{ item }} state=present"
    with_items: "{{ packages }}"

  # Fix slow DNS.
  - name: Fix slow DNS (adapted from Bento).
    lineinfile:
      dest: /etc/sysconfig/network
      regexp: '^RES_OPTIONS'
      line: 'RES_OPTIONS="single-request-reopen"'
      state: present

  - name: Restart network service (explicitly).
    service: name=network state=restarted

  # SSH daemon configuration.
  - name: Configure SSH daemon.
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - { regexp: '^UseDNS', line: 'UseDNS no' }
      - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

  # Vagrant SSH configuration.
  - name: Configure Vagrant .ssh directory.
    file:
      path: /home/vagrant/.ssh
      state: directory
      owner: vagrant
      group: vagrant
      mode: 0700

  - name: Get Vagrant's public key.
    get_url:
      url: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub
      dest: /home/vagrant/.ssh/authorized_keys
      owner: vagrant
      group: vagrant
      mode: 0600

  - include_tasks: virtualbox.yml

